"""Make provider column non-nullable with default email

Revision ID: 876c4c5f159f
Revises: 88c483143439
Create Date: 2025-09-15 12:27:31.229977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876c4c5f159f'
down_revision: Union[str, None] = '88c483143439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update any NULL values to 'email'
    op.execute("UPDATE users SET provider = 'email' WHERE provider IS NULL")
    
    # Then make the column non-nullable with default
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###
