"""Initial migration

Revision ID: d87288c759bc
Revises: 
Create Date: 2025-09-14 14:46:01.487318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87288c759bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_token_expires', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['reset_password_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'reset_password_token_expires')
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
