"""Add provider column and make password nullable

Revision ID: fb711332d4d2
Revises: d87288c759bc
Create Date: 2025-09-15 12:13:55.217269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb711332d4d2'
down_revision: Union[str, None] = 'd87288c759bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the provider column
    op.add_column('users', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the provider column
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
